@startuml
autonumber
participant ":AppointmentMapper" as appointmentMapper
participant "appointment\n:Appointment" as appointment
participant ":VaccineTypeMapper" as vaccineTypeMapper
participant ":SNSUserMapper" as snsUserMapper
participant "appointmentDTO\n:AppointmentDTO" as appointmentDTO
participant "waitingListDTO\n:List<AppointmentDTO>" as waitingListDTO


[o-> appointmentMapper : toDto(waitingList)
activate appointmentMapper

appointmentMapper --> waitingListDTO ** : create()

loop for each appointment in waitingList

appointmentMapper -> appointment : vaccineType=getVaccineType()
activate appointment
deactivate appointment

appointmentMapper -> vaccineTypeMapper : vaccineTypeDTO=toDto(vaccineType)
activate vaccineTypeMapper
ref over vaccineTypeMapper [[US008_SD_VaccineTypeMapper_ToDto.puml]] : US008_SD_VaccineTypeMapper_ToDto
vaccineTypeMapper --> appointmentMapper : vaccineTypeDTO
deactivate vaccineTypeMapper

appointmentMapper -> appointment : snsUser=getSNSUser()
activate appointment
deactivate appointment

appointmentMapper -> snsUserMapper : snsUserDTO=toDto(snsUser)
activate snsUserMapper
ref over snsUserMapper [[US008_SD_SNSUserMapper_ToDto.puml]] : US008_SD_SNSUserMapper_ToDto
snsUserMapper --> appointmentMapper : snsUserDTO
deactivate snsUserMapper

appointmentMapper -> appointment : time=getTime()
activate appointment
deactivate appointment

appointmentMapper -> appointment : date=getDate()
activate appointment
deactivate appointment

appointmentMapper --> appointmentDTO ** : create(vaccineTypeDTO, snsUserDTO, date, time)

appointmentMapper -> waitingListDTO : add(appointmentDTO)
activate waitingListDTO
deactivate waitingListDTO

end

<-- appointmentMapper : waitingListDTO
deactivate appointmentMapper
@enduml